#ifndef ROTATE_IMAGE_H
#define ROTATE_IMAGE_H

#include <inttypes.h>

enum processing_status
{
  PROCESSING_STATUS_PROCESSING_FINISHED_SUCCESSFULLY = 0,
  PROCESSING_STATUS_PROCESSING_FAILED_WHILE_OPENING_SOURCE_IMAGE_FILE,
  PROCESSING_STATUS_PROCESSING_FAILED_WHILE_CONVERTING_FILE_TO_STRUCT_IMAGE,
  PROCESSING_STATUS_PROCESSING_FAILED_WHILE_ROTATING_IMAGE,
  PROCESSING_STATUS_PROCESSING_FAILED_WHILE_OPENING_ROTATED_IMAGE_FILE,
  PROCESSING_STATUS_PROCESSING_FAILED_WHILE_WRITING_TO_ROTATED_IMAGE_FILE,
};

enum processing_status rotate_image( 
	char* source_image_filename,
	char* rotated_image_filename,
	uint_fast8_t* internal_error_code
);

#endif // ROTATE_IMAGE_H