#ifndef ROTATE_IMAGE_H
#define ROTATE_IMAGE_H

#include <stdint.h>

enum program_execution_status
{
  PROGRAM_EXECUTION_STATUS_SUCCESS = 0,
 // PROGRAM_EXECUTION_STATUS_UNKNOWN_SOURCE_IMAGE_FILE_EXTENSION,
  //PROGRAM_EXECUTION_STATUS_UNKNOWN_ROTATED_IMAGE_FILE_EXTENSION,
  PROGRAM_EXECUTION_STATUS_ERROR_WHILE_OPENING_SOURCE_IMAGE_FILE,
  PROGRAM_EXECUTION_STATUS_ERROR_WHILE_CONVERTING_IMAGE_FILE_TO_STRUCT_IMAGE,
  PROGRAM_EXECUTION_STATUS_ERROR_WHILE_ROTATING_IMAGE,
  PROGRAM_EXECUTION_STATUS_ERROR_WHILE_OPENING_ROTATED_IMAGE_FILE,
  PROGRAM_EXECUTION_STATUS_ERROR_WHILE_WRITING_TO_ROTATED_IMAGE_FILE,
};

enum program_execution_status rotate_image(
        char* const source_image_filename,
        char* const input_image,
        uint_fast8_t* const internal_error_code
);

#endif // ROTATE_IMAGE_H
